# Generated by Django 4.0.3 on 2022-03-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(height_field=100, upload_to='products/%Y/%m/%d/', width_field=100),
        ),
    ]
