# Generated by Django 3.2.12 on 2022-03-29 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
